# Service Account as we are using k8s API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-visualizer-sa
  namespace: default

---
# Role for the Service Account
# Note: update this with whatever RBAC config you require.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-visualizer-role
rules:
  - apiGroups: [""]
    resources: 
      - "pods"
      - "services"
      - "configmaps"
      - "secrets"
      - "namespaces"
      - "nodes"
      - "events"
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: 
      - "deployments"
      - "replicasets"
      - "statefulsets"
      - "daemonsets"
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - "jobs"
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - "ingresses"
    verbs: ["get", "list", "watch"]

---

# Role Binding for the Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-visualizer-role-binding
subjects:
  - kind: ServiceAccount
    name: k8s-visualizer-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-visualizer-role
  apiGroup: rbac.authorization.k8s.io

---

# Backend Deployment (now serves WS on 8080 and UI on 5173)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-visualizer-backend
  labels:
    app: k8s-visualizer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-visualizer-backend
  template:
    metadata:
      labels:
        app: k8s-visualizer-backend
    spec:
      serviceAccountName: k8s-visualizer-sa
      containers:
        - name: k8s-visualizer-backend
          image: saumyashah40/k8s-visualize_backend:latest
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 8080
            - name: ui
              containerPort: 8081
---

apiVersion: v1
kind: Service
metadata:
  name: k8s-visualizer-backend-service
spec:
  selector:
    app: k8s-visualizer-backend
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: ui
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer